// AUTO-GENERATED by scripts/extract-manifest.mjs. Do not edit by hand.
export const componentManifest = [
  {
    "kind": "mdx-component",
    "name": "Approval",
    "summary": "Snapshot of an approval decision — what was requested, whether it was approved, who decided, when. Static record, not an interactive widget; for that, fold the decision into the surrounding prose.",
    "category": "agent",
    "spec": {
      "props": [
        {
          "name": "action",
          "type": "string",
          "optional": false,
          "description": "Short description of what was being approved."
        },
        {
          "name": "approved",
          "type": "boolean",
          "optional": true,
          "description": "undefined → pending, true → approved, false → denied."
        },
        {
          "name": "by",
          "type": "string",
          "optional": true,
          "description": "Approver identifier (email, handle)."
        },
        {
          "name": "at",
          "type": "string",
          "optional": true,
          "description": "Timestamp string."
        }
      ]
    },
    "examples": [
      "<Approval\n  action=\"Send findings report to evaluation@bsi.bund.de\"\n  approved={true}\n  by=\"terra@bitcomplete.io\"\n  at=\"2026-05-30 14:02 UTC\"\n/>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "AssistantMessage",
    "summary": "Left-aligned agent turn. Serif body, no bubble, 85% max width. Contains the agent's prose plus any <ToolCall>s the turn produced.",
    "category": "conversation",
    "spec": {
      "props": []
    },
    "examples": [
      "<AssistantMessage>\n  Found three missing SFRs. Let me list them.\n  <ToolCall name=\"search\" status=\"ok\" />\n</AssistantMessage>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Callout",
    "summary": "Coloured aside — info / warning / danger / success / note. Use it to surface \"be careful\", \"important\", or \"good to know\" alongside the main text flow.",
    "category": "emphasis",
    "spec": {
      "props": [
        {
          "name": "type",
          "type": "\"info\" | \"warning\" | \"danger\" | \"success\" | \"note\"",
          "optional": true,
          "default": "\"info\"",
          "description": "Visual tone of the callout."
        },
        {
          "name": "title",
          "type": "string",
          "optional": true,
          "description": "Optional bold title shown above the body."
        }
      ]
    },
    "examples": [
      "<Callout type=\"warning\" title=\"Heads up\">\n  Don't merge this on a Friday.\n</Callout>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Code",
    "summary": "Code block. A fenced markdown block (```lang) renders identically; reach for <Code> when you need the `language` attribute set programmatically (e.g. for client-side highlighters that read it).",
    "category": "code-media",
    "spec": {
      "props": [
        {
          "name": "language",
          "type": "string",
          "optional": true,
          "description": "Optional language hint (e.g. \"go\", \"ts\")."
        }
      ]
    },
    "examples": [
      "<Code language=\"go\">\n  func handle(w http.ResponseWriter, r *http.Request) { ... }\n</Code>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Compare",
    "summary": "Side-by-side panels for weighing 2-3 options. Each child is an <Option>. Use for \"should we do X or Y\" framing, tradeoff exploration, or before/after comparisons.",
    "category": "layout",
    "spec": {
      "props": []
    },
    "examples": [
      "<Compare>\n  <Option label=\"Status quo\">Sync call to Stripe. Easy, blocks request.</Option>\n  <Option label=\"Async webhook\">Queue + worker. Safer p99, more pieces.</Option>\n</Compare>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Conversation",
    "summary": "Rounded container around a chat transcript. Children are <UserMessage>, <AssistantMessage>, <SystemMessage>, optionally <Thinking>. Use to share a session, a worked-through dialogue, a Q&A — anything that reads as turns.",
    "category": "conversation",
    "spec": {
      "props": []
    },
    "examples": [
      "<Conversation>\n  <UserMessage>What's our SLO?</UserMessage>\n  <AssistantMessage>1.5s p99. We've been blowing it.</AssistantMessage>\n</Conversation>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Diagram",
    "summary": "Centred figure wrapper for an inline SVG or image, with an optional caption. The body should be a single visual element — for arbitrary content blocks, use plain markdown.",
    "category": "code-media",
    "spec": {
      "props": [
        {
          "name": "caption",
          "type": "string",
          "optional": true,
          "description": "Caption shown centred below the figure."
        }
      ]
    },
    "examples": [
      "<Diagram caption=\"Request → Queue → Worker → Stripe\">\n  <svg viewBox=\"0 0 200 60\">...</svg>\n</Diagram>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Diff",
    "summary": "Two-column before/after — red bar on the left side, green on the right. Use for explicit change comparisons; for weighing alternatives that aren't a strict before→after, use <Compare>.",
    "category": "data",
    "spec": {
      "props": [
        {
          "name": "before",
          "type": "React.ReactNode",
          "optional": false,
          "description": "Left column content (the previous state)."
        },
        {
          "name": "after",
          "type": "React.ReactNode",
          "optional": false,
          "description": "Right column content (the new state)."
        },
        {
          "name": "beforeLabel",
          "type": "string",
          "optional": true,
          "default": "\"Before\"",
          "description": "Override the left-column label."
        },
        {
          "name": "afterLabel",
          "type": "string",
          "optional": true,
          "default": "\"After\"",
          "description": "Override the right-column label."
        }
      ]
    },
    "examples": [
      "<Diff\n  before=\"Synchronous Stripe call from request handler\"\n  after=\"Worker reads from SQS, retries with token bucket\"\n/>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Event",
    "summary": "One marker on a <Timeline>. Either the time, the title, or both — pick whichever reads cleanly for your sequence.",
    "category": "chronological",
    "spec": {
      "props": [
        {
          "name": "time",
          "type": "string",
          "optional": true,
          "description": "When it happened (free-form string)."
        },
        {
          "name": "tone",
          "type": "\"ok\" | \"info\" | \"warn\" | \"err\"",
          "optional": true,
          "description": "Marker dot colour."
        },
        {
          "name": "title",
          "type": "string",
          "optional": true,
          "description": "Short headline."
        }
      ]
    },
    "examples": [
      "<Event time=\"2026-05-30\" title=\"Tag 19 reconciled\" tone=\"ok\">\n  BrowserOrBearer middleware live.\n</Event>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Finding",
    "summary": "Single bulleted finding — issue, risk, surprise, or gotcha. Severity colours the bullet. Use a sequence of <Finding>s for review notes, audit results, postmortem observations.",
    "category": "agent",
    "spec": {
      "props": [
        {
          "name": "code",
          "type": "string",
          "optional": true,
          "description": "Optional short identifier (e.g. ticket / rule code)."
        },
        {
          "name": "title",
          "type": "string",
          "optional": false,
          "description": "Short headline."
        },
        {
          "name": "severity",
          "type": "\"info\" | \"low\" | \"medium\" | \"high\" | \"critical\"",
          "optional": true,
          "default": "\"medium\"",
          "description": "Visual + semantic weight."
        }
      ]
    },
    "examples": [
      "<Finding code=\"BILL-014\" title=\"Retries can DDoS Stripe\" severity=\"high\">\n  3× exponential backoff hits Stripe hardest when it's already\n  slow. Move retries to the worker with a token bucket.\n</Finding>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Findings",
    "summary": "Optional grouping wrapper around several <Finding>s. Tightens the vertical spacing so a long list reads as one block.",
    "category": "agent",
    "spec": {
      "props": []
    },
    "examples": [
      "<Findings>\n  <Finding title=\"Missing key destruction\" severity=\"high\" />\n  <Finding title=\"Stale algorithm reference\" severity=\"medium\" />\n</Findings>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "KPI",
    "summary": "Big-number metric: large light-serif value, uppercase sans label below, optional trend annotation. Lives inside a <KPIGroup>.",
    "category": "data",
    "spec": {
      "props": [
        {
          "name": "value",
          "type": "string | number",
          "optional": false,
          "description": "The number (or short string) shown large."
        },
        {
          "name": "label",
          "type": "string",
          "optional": false,
          "description": "Caption under the value. Kept short."
        },
        {
          "name": "trend",
          "type": "string",
          "optional": true,
          "description": "Optional sub-line — direction, comparison, \"projected\", etc."
        },
        {
          "name": "tone",
          "type": "\"ok\" | \"info\" | \"default\" | \"warn\" | \"err\"",
          "optional": true,
          "default": "\"default\"",
          "description": "Colour cue for the value."
        }
      ]
    },
    "examples": [
      "<KPI value=\"99.95%\" label=\"uptime\" tone=\"ok\" trend=\"↑ 0.02 vs last week\" />"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "KPIGroup",
    "summary": "Responsive row of <KPI> children. Use to surface a handful of top-line metrics at the top of a status update or report.",
    "category": "data",
    "spec": {
      "props": []
    },
    "examples": [
      "<KPIGroup>\n  <KPI value=\"8.3s\" label=\"p99 today\" tone=\"err\" />\n  <KPI value=\"42ms\" label=\"p99 after\" tone=\"ok\" trend=\"projected\" />\n</KPIGroup>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Option",
    "summary": "One panel inside a <Compare>. The label is the short heading; the children are the supporting argument.",
    "category": "layout",
    "spec": {
      "props": [
        {
          "name": "label",
          "type": "string",
          "optional": false,
          "description": "Short heading for this option."
        }
      ]
    },
    "examples": [
      "<Option label=\"Async webhook (proposed)\">\n  Request handler queues a job and returns immediately.\n</Option>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Quote",
    "summary": "Pull quote — italic serif body with a thin left rule and optional attribution. Use for important things someone said, never for the agent's own paragraphs.",
    "category": "emphasis",
    "spec": {
      "props": [
        {
          "name": "author",
          "type": "string",
          "optional": true,
          "description": "Optional attribution shown under the quote."
        }
      ]
    },
    "examples": [
      "<Quote author=\"Rich Hickey\">\n  Simple is not the same as easy.\n</Quote>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Section",
    "summary": "Major section wrapper with an optional title. Mostly redundant with a plain `## H2` in markdown — reach for it when you need an `id` anchor or a wrapping container for styling/spacing.",
    "category": "layout",
    "spec": {
      "props": [
        {
          "name": "title",
          "type": "string",
          "optional": true,
          "description": "Optional H2 rendered above the body."
        }
      ]
    },
    "examples": [
      "<Section title=\"Why now\" id=\"why-now\">\n  We've blown the SLO every weekday this month.\n</Section>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Status",
    "summary": "Inline state indicator: a coloured dot + label. Distinct from <Tag> in that the dot communicates a binary/categorical state at a glance.",
    "category": "data",
    "spec": {
      "props": [
        {
          "name": "state",
          "type": "\"ok\" | \"info\" | \"warn\" | \"err\"",
          "optional": false,
          "description": "Which state colour to show."
        }
      ]
    },
    "examples": [
      "<Status state=\"ok\">In progress</Status>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Step",
    "summary": "One row inside a <Steps>. The title is required; the body (children) is optional supporting detail. Status colours the indicator and pill.",
    "category": "layout",
    "spec": {
      "props": [
        {
          "name": "title",
          "type": "string",
          "optional": false,
          "description": "Short summary of what the step is."
        },
        {
          "name": "status",
          "type": "\"todo\" | \"doing\" | \"done\" | \"blocked\"",
          "optional": true,
          "description": "Visual state. Defaults to \"todo\"."
        }
      ]
    },
    "examples": [
      "<Step title=\"Add the `billing-events` queue\" status=\"done\">\n  SQS FIFO, dead-letter queue with 5-attempt cap.\n</Step>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Steps",
    "summary": "Plan-card list of <Step> children. Wrap a sequence of actions / milestones whose state matters (todo / doing / done / blocked). For a flat unordered list of bullets, use plain markdown instead.",
    "category": "layout",
    "spec": {
      "props": [
        {
          "name": "title",
          "type": "string",
          "optional": true,
          "description": "Optional header label rendered inside the card."
        }
      ]
    },
    "examples": [
      "<Steps title=\"Cutover plan\">\n  <Step title=\"Add the queue\" status=\"done\">SQS FIFO with DLQ.</Step>\n  <Step title=\"Carve out worker\" status=\"doing\">cmd/billing-worker.</Step>\n  <Step title=\"Cut over + watch\" status=\"todo\" />\n</Steps>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "SystemMessage",
    "summary": "Centred system notice — \"Agent connected to repo\", \"Session resumed\", etc. Small muted pill.",
    "category": "conversation",
    "spec": {
      "props": []
    },
    "examples": [
      "<SystemMessage>Agent connected to document repository</SystemMessage>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Tag",
    "summary": "Small inline pill for short labels — \"v2\", \"draft\", \"behind flag\". Distinct from <Status> in that there's no dot and the colour is just decorative.",
    "category": "data",
    "spec": {
      "props": [
        {
          "name": "color",
          "type": "\"info\" | \"warning\" | \"danger\" | \"success\" | \"default\"",
          "optional": true,
          "default": "\"default\"",
          "description": "Pill colour."
        }
      ]
    },
    "examples": [
      "Status: <Tag color=\"warning\">latency-bound</Tag>."
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Thinking",
    "summary": "Tiny italic \"Thinking\" indicator placed above an <AssistantMessage>. Use to signal the agent is reasoning before it replies — usually paired with an empty assistant turn in a live demo.",
    "category": "conversation",
    "spec": {
      "props": []
    },
    "examples": [
      "<Thinking>Thinking…</Thinking>\n<AssistantMessage>Here's what I found.</AssistantMessage>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "Timeline",
    "summary": "Vertical event sequence with a spine and marker dots. Use for milestones, release timelines, postmortem chronologies — anything ordered by when.",
    "category": "chronological",
    "spec": {
      "props": []
    },
    "examples": [
      "<Timeline>\n  <Event time=\"Week 1\" title=\"Queue + worker land behind feature flag\" />\n  <Event time=\"Week 2\" title=\"Cutover ramp begins\" tone=\"ok\" />\n</Timeline>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "TLDR",
    "summary": "Summary box at the top of a document. Use one — at most one — per share to let readers grasp the whole thing in a sentence before deciding to dive in.",
    "category": "layout",
    "spec": {
      "props": []
    },
    "examples": [
      "<TLDR>\n  Migrating billing off the request path drops p99 from 8s to 40ms.\n  Two PRs, behind a feature flag.\n</TLDR>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "ToolCall",
    "summary": "Single tool invocation row. Collapsible: clicking the row opens args + output. Failed calls open by default and gain the \"failed ·\" timing prefix.",
    "category": "agent",
    "spec": {
      "props": [
        {
          "name": "name",
          "type": "string",
          "optional": false
        },
        {
          "name": "label",
          "type": "string",
          "optional": true,
          "description": "Human-readable label override. Falls back to `name`."
        },
        {
          "name": "status",
          "type": "\"running\" | \"ok\" | \"fail\" | \"skip\"",
          "optional": true,
          "default": "\"ok\""
        },
        {
          "name": "timing",
          "type": "string",
          "optional": true
        },
        {
          "name": "args",
          "type": "string",
          "optional": true
        },
        {
          "name": "children",
          "type": "React.ReactNode",
          "optional": true
        }
      ]
    },
    "examples": [
      "<ToolCall name=\"bash\" status=\"ok\" timing=\"0.4s\" args='go test ./...'>\n  ok  github.com/bitcomplete/pin/internal/auth  0.418s\n</ToolCall>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "ToolCallGroup",
    "summary": "Rounded frame around several adjacent <ToolCall>s. Pure visual grouping — no header, no shared toggle. For a labelled, collapsible parent (e.g. \"Running 3 in parallel\"), use <ToolTree> instead.",
    "category": "agent",
    "spec": {
      "props": [
        {
          "name": "className",
          "type": "string",
          "optional": true,
          "description": "Extra classes; rarely needed."
        },
        {
          "name": "children",
          "type": "React.ReactNode",
          "optional": true
        }
      ]
    },
    "examples": [
      "<ToolCallGroup>\n  <ToolCall name=\"search\" status=\"ok\" />\n  <ToolCall name=\"read\" status=\"ok\" />\n  <ToolCall name=\"edit\" status=\"ok\" />\n</ToolCallGroup>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "ToolTree",
    "summary": "Labelled, collapsible group of tool calls — the \"Running N in parallel\" pattern. Header summary at top, L-connectored children inside. Use when the calls share a higher-level purpose worth naming; for an unlabelled visual frame, use <ToolCallGroup>.",
    "category": "agent",
    "spec": {
      "props": [
        {
          "name": "label",
          "type": "string",
          "optional": true,
          "default": "\"Running tools\"",
          "description": "Header shown above the children."
        },
        {
          "name": "defaultOpen",
          "type": "boolean",
          "optional": true,
          "description": "Open by default? Defaults to false."
        },
        {
          "name": "children",
          "type": "React.ReactNode",
          "optional": true
        }
      ]
    },
    "examples": [
      "<ToolTree label=\"Running 3 tasks in parallel\">\n  <ToolCall name=\"search\" status=\"ok\" />\n  <ToolCall name=\"read\" status=\"ok\" />\n  <ToolCall name=\"grep\" status=\"ok\" />\n</ToolTree>"
    ]
  },
  {
    "kind": "mdx-component",
    "name": "UserMessage",
    "summary": "Right-aligned chat bubble for the human's turn. Sans, 75% max width. Markdown inside renders normally.",
    "category": "conversation",
    "spec": {
      "props": []
    },
    "examples": [
      "<UserMessage>Can you list the SFRs missing from the mapping?</UserMessage>"
    ]
  }
] as const;
