// Read dist/styles.css and write src/components/styles.ts exporting it as a
// string literal. tsup picks the .ts up and inlines it into the IIFE so the
// compiled bundle ships its own stylesheet — no filesystem access at run
// time.

import { readFileSync, writeFileSync } from "node:fs";

const css = readFileSync("dist/styles.css", "utf8");
const escaped = "`" + css.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";

writeFileSync(
  "src/components/styles.ts",
  `// AUTO-GENERATED by scripts/embed-css.mjs. Edit src/styles/tailwind.css instead.\n` +
    `export const stylesheet = ${escaped};\n`,
);

console.log(`embed-css: wrote ${css.length} bytes → src/components/styles.ts`);
